name: Log-Accounting-SVK
version: 0.05
abstract: Accounting SVK repository
author: Kang-min Liu <gugod@gugod.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  Algorithm::Accounting: 0
  SVK: 0
  Spiffy: 0
  Graph::SocialMap: 0.1
  Graph::Writer::GraphViz: 0.08
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
